import { Validators } from '@angular/forms';

import { ProductTypeEnum } from '../../../../../../shared/api/auth/data-contracts';
import { validateIf } from '../../../../../../shared/form validators/validate-if.validator';
import { SLUG_PATTERN } from '../../../../../../shared/helpers/slug-pattern';

export const ProductsControlsConfigForm: { [p: string]: any } = {
  name_i18n: [null, [Validators.required]],
  description_i18n: [null],
  isActive: [true, [Validators.required]],
  productType: [ProductTypeEnum.GROCERY, [Validators.required]],
  code: [null, [Validators.required]],
  note_internal: [null],
  note_external: [null],
  gtin: [null, [Validators.required]],
  sku: [null, [Validators.required]],
  ean: [null, [Validators.required]],
  slug: [null, [Validators.pattern(SLUG_PATTERN), Validators.required, Validators.maxLength(400), Validators.minLength(3)]],
  isCustomAgeRestriction: [false, [Validators.required]],
  ageRestriction: [null, [validateIf('isCustomAgeRestriction')]],
  isApproved: [false, [Validators.required]],
  isPickup: [false, [Validators.required]],
  isPickAndDrive: [null, [Validators.required]],
  isOnlineShipment: [null, [Validators.required]],
  isPublic: [null, [Validators.required]],
  isFairTrade: [null, [Validators.required]],
  isPublicDateTime: [null, [Validators.required]],
  productBrandCode: [null],
  productSubcategoryCode: [null, [Validators.required]],
  productCategoryCode: [null, [Validators.required]],
  imageUrls: [null, [Validators.required]],
  weight: [null, [Validators.required, Validators.min(1)]],
  productUnitCode: [null, [Validators.required]],
  baseUnitCode: [null, [Validators.required]],
  productMeasurement: [null, [Validators.required, Validators.min(1)]],
  baseMeasurement: [null, [Validators.required, Validators.min(1)]],
  defaultPrice: [null, [Validators.required, Validators.min(0.1)]],
  costPrice: [null],
  chargeTax: [null, [Validators.required]],
  vatCode: [null, [Validators.required]],
  deposit: [null],
  tags_i18n: [null],
  manufacturer_i18n: [null],
  special_notes_i18n: [null],
  metaData: [null],
  productAttributes: [null],
  isConsultationRecommended: [null],
  productLegalCode: [null],
};
