import { AddressTypeEnum, StoreDto } from '../../../../shared/api/data-contracts';

/* Need to be updated */
export interface PaymentMethodEntity {
  logoUrl: string;
  cardNo: string;
  cardHolder: string;
  expires: string;
  isDefault?: boolean;
}

// export const ProductsData: ProductDto[] = [
//   {
//     productId: '1',
//     linkId: '1',
//     discount: '2,93 €',
//     imageUrl: 'rosso.svg',
//     name_i18n: 'Barilla Pesto Rosso 200g',
//     price: '2,93 €',
//     salePrice: '2,93 €',
//     regularPrice: '2,93 €',
//     subcategoryName: '',
//     subcategoryCode: '',
//     categoryCode: '',
//     basePrice: '1,47 €',
//     inCart: 1,
//     baseSize: '',
//     productSize: '',
//     vatPercent: 1,
//     isAlcohol: true,
//     vat: 'Vat 7 %',
//     isCustomAgeRestriction: true,
//     outOfStock: true,
//     baseSizeDetailed: {},
//     productSizeDetailed: null,
//     productType: null
//   },
//   {
//     productId: '2',
//     linkId: '2',
//     discount: '2,93 €',
//     imageUrl: 'crisp.svg',
//     name_i18n: 'Ritter Sport Weiß + Crisp 100g',
//     price: '2,93 €',
//     salePrice: '',
//     regularPrice: '2,93 €',
//     subcategoryName: '',
//     subcategoryCode: '',
//     categoryCode: '',
//     inCart: 3,
//     basePrice: '1,47 €',
//     baseSize: '',
//     productSize: '',
//     vatPercent: 1,
//     isAlcohol: true,
//     isCustomAgeRestriction: true,
//     vat: 'Vat 7 %',
//     outOfStock: false,
//   },
//   {
//     productId: '3',
//     linkId: '3',
//     discount: '2,93 €',
//     imageUrl: 'fest.svg',
//     name_i18n: 'Kartoffel Bio Festkochend',
//     price: '2,93 €',
//     salePrice: '2,93 €',
//     regularPrice: '1,66 €',
//     subcategoryName: '',
//     subcategoryCode: '',
//     categoryCode: '',
//     inCart: 1,
//     basePrice: '1,47 €',
//     baseSize: '',
//     productSize: '',
//     vatPercent: 1,
//     isAlcohol: true,
//     isCustomAgeRestriction: true,
//     vat: 'Vat 7 %',
//     outOfStock: false,
//   },
// ];

// export const ProductsDetailData: ProductDetailsDto[] = [
//   {
//     productId: '1',
//     linkId: '1',
//     discount: '2,93 €',
//     imageUrl: 'rosso.svg',
//     name_i18n: 'Barilla Pesto Rosso 200g',
//     price: '2,93 €',
//     salePrice: '2,93 €',
//     regularPrice: '2,93 €',
//     subcategoryName: '',
//     subcategoryCode: '',
//     categoryCode: '',
//     categoryName: '',
//     basePrice: '1,47 €',
//     inCart: 1,
//     baseSize: '',
//     productSize: '',
//     vatPercent: 1,
//     isAlcohol: true,
//     vat: 'Vat 7 %',
//     alcoholValue: 'string',
//     description_i18n: 'string',
//     imageUrls: ['1.jpg', '2.jpg'],
//     ean: 10,
//     sku: 'string',
//     nutriScore: NutriScoreEnum.A,
//     deposit: 'deposit',
//     weight: 1,
//     isCustomAgeRestriction: true,
//     nutritional_data: undefined,
//     productBrandName_i18n: '',
//     manufacturer_i18n: '',
//     outOfStock: false,
//   },
//   {
//     productId: '2',
//     linkId: '2',
//     discount: '2,93 €',
//     imageUrl: 'crisp.svg',
//     name_i18n: 'Ritter Sport Weiß + Crisp 100g',
//     price: '2,93 €',
//     salePrice: '',
//     regularPrice: '2,93 €',
//     subcategoryName: '',
//     subcategoryCode: '',
//     categoryCode: '',
//     categoryName: '',
//     inCart: 3,
//     basePrice: '1,47 €',
//     baseSize: '',
//     productSize: '',
//     vatPercent: 1,
//     isAlcohol: true,
//     vat: 'Vat 7 %',
//     alcoholValue: 'string',
//     description_i18n: 'string',
//     imageUrls: ['1.jpg', '2.jpg'],
//     ean: 10,
//     sku: 'string',
//     nutriScore: NutriScoreEnum.A,
//     deposit: 'deposit',
//     weight: 1,
//     isCustomAgeRestriction: true,
//     nutritional_data: undefined,
//     productBrandName_i18n: '',
//     manufacturer_i18n: '',
//     outOfStock: false,
//   },
//   {
//     productId: '3',
//     linkId: '3',
//     discount: '2,93 €',
//     imageUrl: 'fest.svg',
//     name_i18n: 'Kartoffel Bio Festkochend',
//     price: '2,93 €',
//     salePrice: '2,93 €',
//     regularPrice: '1,66 €',
//     subcategoryName: '',
//     subcategoryCode: '',
//     categoryCode: '',
//     categoryName: '',
//     inCart: 1,
//     basePrice: '1,47 €',
//     baseSize: '',
//     productSize: '',
//     vatPercent: 1,
//     isAlcohol: true,
//     vat: 'Vat 7 %',
//     alcoholValue: 'string',
//     description_i18n: 'string',
//     imageUrls: ['1.jpg', '2.jpg'],
//     ean: 10,
//     sku: 'string',
//     nutriScore: NutriScoreEnum.A,
//     deposit: 'deposit',
//     weight: 1,
//     isCustomAgeRestriction: true,
//     nutritional_data: undefined,
//     productBrandName_i18n: '',
//     manufacturer_i18n: '',
//     outOfStock: false,
//   },
//   {
//     productId: '4',
//     linkId: '4',
//     discount: '2,93 €',
//     imageUrl: 'rosso.svg',
//     name_i18n: 'Barilla Pesto Rosso 200g',
//     price: '2,93 €',
//     salePrice: '2,93 €',
//     regularPrice: '2,93 €',
//     subcategoryName: '',
//     subcategoryCode: '',
//     categoryCode: '',
//     categoryName: '',
//     basePrice: '1,47 €',
//     inCart: 1,
//     baseSize: '',
//     productSize: '',
//     vatPercent: 1,
//     isAlcohol: true,
//     vat: 'Vat 7 %',
//     alcoholValue: 'string',
//     description_i18n: 'string',
//     imageUrls: ['1.jpg', '2.jpg'],
//     ean: 10,
//     sku: 'string',
//     nutriScore: NutriScoreEnum.A,
//     deposit: 'deposit',
//     weight: 1,
//     isCustomAgeRestriction: true,
//     nutritional_data: undefined,
//     productBrandName_i18n: '',
//     manufacturer_i18n: '',
//     outOfStock: false,
//   },
//   {
//     productId: '5',
//     linkId: '5',
//     discount: '2,93 €',
//     imageUrl: 'crisp.svg',
//     name_i18n: 'Ritter Sport Weiß + Crisp 100g',
//     price: '2,93 €',
//     salePrice: '',
//     regularPrice: '2,93 €',
//     subcategoryName: '',
//     subcategoryCode: '',
//     categoryCode: '',
//     categoryName: '',
//     inCart: 3,
//     basePrice: '1,47 €',
//     baseSize: '',
//     productSize: '',
//     vatPercent: 1,
//     isAlcohol: true,
//     vat: 'Vat 7 %',
//     alcoholValue: 'string',
//     description_i18n: 'string',
//     imageUrls: ['1.jpg', '2.jpg'],
//     ean: 10,
//     sku: 'string',
//     nutriScore: NutriScoreEnum.A,
//     deposit: 'deposit',
//     weight: 1,
//     isCustomAgeRestriction: true,
//     nutritional_data: undefined,
//     productBrandName_i18n: '',
//     manufacturer_i18n: '',
//     outOfStock: false,
//   },
//   {
//     productId: '6',
//     linkId: '6',
//     discount: '2,93 €',
//     imageUrl: 'fest.svg',
//     name_i18n: 'Kartoffel Bio Festkochend',
//     price: '2,93 €',
//     salePrice: '2,93 €',
//     regularPrice: '1,66 €',
//     subcategoryName: '',
//     subcategoryCode: '',
//     categoryCode: '',
//     categoryName: '',
//     inCart: 1,
//     basePrice: '1,47 €',
//     baseSize: '',
//     productSize: '',
//     vatPercent: 1,
//     isAlcohol: true,
//     vat: 'Vat 7 %',
//     alcoholValue: 'string',
//     description_i18n: 'string',
//     imageUrls: ['1.jpg', '2.jpg'],
//     ean: 10,
//     sku: 'string',
//     nutriScore: NutriScoreEnum.A,
//     deposit: 'deposit',
//     weight: 1,
//     isCustomAgeRestriction: true,
//     nutritional_data: undefined,
//     productBrandName_i18n: '',
//     manufacturer_i18n: '',
//     outOfStock: false,
//   },
//   {
//     productId: '7',
//     linkId: '7',
//     discount: '2,93 €',
//     imageUrl: 'rosso.svg',
//     name_i18n: 'Barilla Pesto Rosso 200g',
//     price: '2,93 €',
//     salePrice: '2,93 €',
//     regularPrice: '2,93 €',
//     subcategoryName: '',
//     subcategoryCode: '',
//     categoryCode: '',
//     categoryName: '',
//     basePrice: '1,47 €',
//     inCart: 1,
//     baseSize: '',
//     productSize: '',
//     vatPercent: 1,
//     isAlcohol: true,
//     vat: 'Vat 7 %',
//     alcoholValue: 'string',
//     description_i18n: 'string',
//     imageUrls: ['1.jpg', '2.jpg'],
//     ean: 10,
//     sku: 'string',
//     nutriScore: NutriScoreEnum.A,
//     deposit: 'deposit',
//     weight: 1,
//     isCustomAgeRestriction: true,
//     nutritional_data: undefined,
//     productBrandName_i18n: '',
//     manufacturer_i18n: '',
//     outOfStock: false,
//   },
//   {
//     productId: '8',
//     linkId: '8',
//     discount: '2,93 €',
//     imageUrl: 'crisp.svg',
//     name_i18n: 'Ritter Sport Weiß + Crisp 100g',
//     price: '2,93 €',
//     salePrice: '',
//     regularPrice: '2,93 €',
//     subcategoryName: '',
//     subcategoryCode: '',
//     categoryCode: '',
//     categoryName: '',
//     inCart: 3,
//     basePrice: '1,47 €',
//     baseSize: '',
//     productSize: '',
//     vatPercent: 1,
//     isAlcohol: true,
//     vat: 'Vat 7 %',
//     alcoholValue: 'string',
//     description_i18n: 'string',
//     imageUrls: ['1.jpg', '2.jpg'],
//     ean: 10,
//     sku: 'string',
//     nutriScore: NutriScoreEnum.A,
//     deposit: 'deposit',
//     weight: 1,
//     isCustomAgeRestriction: true,
//     nutritional_data: undefined,
//     productBrandName_i18n: '',
//     manufacturer_i18n: '',
//     outOfStock: false,
//   },
//   {
//     productId: '9',
//     linkId: '9',
//     discount: '2,93 €',
//     imageUrl: 'fest.svg',
//     name_i18n: 'Kartoffel Bio Festkochend',
//     price: '2,93 €',
//     salePrice: '2,93 €',
//     regularPrice: '1,66 €',
//     subcategoryName: '',
//     subcategoryCode: '',
//     categoryCode: '',
//     categoryName: '',
//     inCart: 1,
//     basePrice: '1,47 €',
//     baseSize: '',
//     productSize: '',
//     vatPercent: 1,
//     isAlcohol: true,
//     vat: 'Vat 7 %',
//     alcoholValue: 'string',
//     description_i18n: 'string',
//     imageUrls: ['1.jpg', '2.jpg'],
//     ean: 10,
//     sku: 'string',
//     nutriScore: NutriScoreEnum.A,
//     deposit: 'deposit',
//     weight: 1,
//     isCustomAgeRestriction: true,
//     nutritional_data: undefined,
//     productBrandName_i18n: '',
//     manufacturer_i18n: '',
//     outOfStock: false,
//   },
//   {
//     productId: '10',
//     linkId: '10',
//     discount: '2,93 €',
//     imageUrl: 'rosso.svg',
//     name_i18n: 'Barilla Pesto Rosso 200g',
//     price: '2,93 €',
//     salePrice: '2,93 €',
//     regularPrice: '2,93 €',
//     subcategoryName: '',
//     subcategoryCode: '',
//     categoryCode: '',
//     categoryName: '',
//     basePrice: '1,47 €',
//     inCart: 1,
//     baseSize: '',
//     productSize: '',
//     vatPercent: 1,
//     isAlcohol: true,
//     vat: 'Vat 7 %',
//     alcoholValue: 'string',
//     description_i18n: 'string',
//     imageUrls: ['1.jpg', '2.jpg'],
//     ean: 10,
//     sku: 'string',
//     nutriScore: NutriScoreEnum.A,
//     deposit: 'deposit',
//     weight: 1,
//     isCustomAgeRestriction: true,
//     nutritional_data: undefined,
//     productBrandName_i18n: '',
//     manufacturer_i18n: '',
//     outOfStock: false,
//   },
//   {
//     productId: '11',
//     linkId: '11',
//     discount: '2,93 €',
//     imageUrl: 'crisp.svg',
//     name_i18n: 'Ritter Sport Weiß + Crisp 100g',
//     price: '2,93 €',
//     salePrice: '',
//     regularPrice: '2,93 €',
//     subcategoryName: '',
//     subcategoryCode: '',
//     categoryCode: '',
//     categoryName: '',
//     inCart: 3,
//     basePrice: '1,47 €',
//     baseSize: '',
//     productSize: '',
//     vatPercent: 1,
//     isAlcohol: true,
//     vat: 'Vat 7 %',
//     alcoholValue: 'string',
//     description_i18n: 'string',
//     imageUrls: ['1.jpg', '2.jpg'],
//     ean: 10,
//     sku: 'string',
//     nutriScore: NutriScoreEnum.A,
//     deposit: 'deposit',
//     weight: 1,
//     isCustomAgeRestriction: true,
//     nutritional_data: undefined,
//     productBrandName_i18n: '',
//     manufacturer_i18n: '',
//     outOfStock: false,
//   },
//   {
//     productId: '12',
//     linkId: '12',
//     discount: '2,93 €',
//     imageUrl: 'fest.svg',
//     name_i18n: 'Kartoffel Bio Festkochend',
//     price: '2,93 €',
//     salePrice: '2,93 €',
//     regularPrice: '1,66 €',
//     subcategoryName: '',
//     subcategoryCode: '',
//     categoryCode: '',
//     categoryName: '',
//     inCart: 1,
//     basePrice: '1,47 €',
//     baseSize: '',
//     productSize: '',
//     vatPercent: 1,
//     isAlcohol: true,
//     vat: 'Vat 7 %',
//     alcoholValue: 'string',
//     description_i18n: 'string',
//     imageUrls: ['1.jpg', '2.jpg'],
//     ean: 10,
//     sku: 'string',
//     nutriScore: NutriScoreEnum.A,
//     deposit: 'deposit',
//     weight: 1,
//     isCustomAgeRestriction: true,
//     nutritional_data: undefined,
//     productBrandName_i18n: '',
//     manufacturer_i18n: '',
//     outOfStock: false,
//   },
//   {
//     productId: '13',
//     linkId: '13',
//     discount: '2,93 €',
//     imageUrl: 'rosso.svg',
//     name_i18n: 'Barilla Pesto Rosso 200g',
//     price: '2,93 €',
//     salePrice: '2,93 €',
//     regularPrice: '2,93 €',
//     subcategoryName: '',
//     subcategoryCode: '',
//     categoryCode: '',
//     categoryName: '',
//     basePrice: '1,47 €',
//     inCart: 1,
//     baseSize: '',
//     productSize: '',
//     vatPercent: 1,
//     isAlcohol: true,
//     vat: 'Vat 7 %',
//     alcoholValue: 'string',
//     description_i18n: 'string',
//     imageUrls: ['1.jpg', '2.jpg'],
//     ean: 10,
//     sku: 'string',
//     nutriScore: NutriScoreEnum.A,
//     deposit: 'deposit',
//     weight: 1,
//     isCustomAgeRestriction: true,
//     nutritional_data: undefined,
//     productBrandName_i18n: '',
//     manufacturer_i18n: '',
//     outOfStock: false,
//   },
//   {
//     productId: '14',
//     linkId: '14',
//     discount: '2,93 €',
//     imageUrl: 'crisp.svg',
//     name_i18n: 'Ritter Sport Weiß + Crisp 100g',
//     price: '2,93 €',
//     salePrice: '',
//     regularPrice: '2,93 €',
//     subcategoryName: '',
//     subcategoryCode: '',
//     categoryCode: '',
//     categoryName: '',
//     inCart: 3,
//     basePrice: '1,47 €',
//     baseSize: '',
//     productSize: '',
//     vatPercent: 1,
//     isAlcohol: true,
//     vat: 'Vat 7 %',
//     alcoholValue: 'string',
//     description_i18n: 'string',
//     imageUrls: ['1.jpg', '2.jpg'],
//     ean: 10,
//     sku: 'string',
//     nutriScore: NutriScoreEnum.A,
//     deposit: 'deposit',
//     weight: 1,
//     isCustomAgeRestriction: true,
//     nutritional_data: undefined,
//     productBrandName_i18n: '',
//     manufacturer_i18n: '',
//     outOfStock: false,
//   },
//   {
//     productId: '15',
//     linkId: '15',
//     discount: '2,93 €',
//     imageUrl: 'fest.svg',
//     name_i18n: 'Kartoffel Bio Festkochend',
//     price: '2,93 €',
//     salePrice: '2,93 €',
//     regularPrice: '1,66 €',
//     subcategoryName: '',
//     subcategoryCode: '',
//     categoryCode: '',
//     categoryName: '',
//     inCart: 1,
//     basePrice: '1,47 €',
//     baseSize: '',
//     productSize: '',
//     vatPercent: 1,
//     isAlcohol: true,
//     vat: 'Vat 7 %',
//     alcoholValue: 'string',
//     description_i18n: 'string',
//     imageUrls: ['1.jpg', '2.jpg'],
//     ean: 10,
//     sku: 'string',
//     nutriScore: NutriScoreEnum.A,
//     deposit: 'deposit',
//     weight: 1,
//     isCustomAgeRestriction: true,
//     nutritional_data: undefined,
//     productBrandName_i18n: '',
//     manufacturer_i18n: '',
//     outOfStock: false,
//   },
// ];

export const StoreData: StoreDto = {
  address: '',
  distance: 'Ölmühlenweg 4 · 0,50 km',
  id: '1',
  code: '',
  isPickup: true,
  isDelivery: true,
  isOnlineShipment: true,
  logoUrl: 'company-logo',
  name_public_long_i18n: "Meyer's Frischecenter",
  name_public_short_i18n: '',
  openingTime: '07:00–21:00',
  vendorType: {
    code: '',
    name_i18n: 'Supermarkt',
  },
  isOpen: true,
  deliveryTimeInMinutes: 45,
  deliveryDate: 10,
  isInstantDelivery: true,
  timeZone: '',
  streetName: '',
  streetNumber: '',
  replacementAllowed: false,
  isStartPickJobWithoutDriverAllowed: false,
  replacementMaxTime: 0,
  replacementMaxAttempts: 0,
};

export const DeliveryStoreData: any[] = [
  {
    id: '1',
    isActive: true,
    name_i18n: 'Meyer’s Frischecenter',
    name_public_long_i18n: 'Meyer’s Frischecenter',
    name_public_short_i18n: 'Supermarket',
    logoUrl: 'company1.svg',
    vendorType: {
      id: '1',
      isActive: true,
      name_i18n: 'Supermarket',
    },
    productLink: [
      {
        id: '1',
        isActive: true,
      },
    ],
    addresses: [
      {
        id: '1',
        isActive: true,
        streets: ['Ferdinandstraße 32'],
        city: 'Hamburg',
        addressType: 'MAIN',
      },
      {
        id: '2',
        isActive: true,
        streets: ['Ferdinandstraße 32'],
        city: 'Hamburg',
        addressType: 'MAIN',
      },
      {
        id: '3',
        isActive: true,
        streets: ['Ferdinandstraße 32'],
        city: 'Hamburg',
        addressType: 'MAIN',
      },
      {
        id: '4',
        isActive: true,
        streets: ['Ferdinandstraße 32'],
        city: 'Hamburg',
        addressType: 'MAIN',
      },
      {
        id: '5',
        isActive: true,
        streets: ['Ferdinandstraße 32'],
        city: 'Hamburg',
        addressType: 'MAIN',
      },
      {
        id: '6',
        isActive: true,
        streets: ['Ferdinandstraße 32'],
        city: 'Hamburg',
        addressType: 'MAIN',
      },
    ],
  },
  {
    id: '2',
    isActive: true,
    name_i18n: 'REWE Center',
    name_public_long_i18n: 'REWE Center',
    name_public_short_i18n: 'REWE Center',
    logoUrl: 'company2.svg',
    vendorType: {
      id: '2',
      isActive: true,
      name_i18n: 'Supermarket',
    },
    productLink: [
      {
        id: '2',
        isActive: true,
      },
    ],
    addresses: [
      {
        id: '7',
        isActive: true,
        streets: ['Ferdinandstraße 32'],
        city: 'Hamburg',
        addressType: 'MAIN',
      },
      {
        id: '8',
        isActive: true,
        streets: ['Ferdinandstraße 32'],
        city: 'Hamburg',
        addressType: 'MAIN',
      },
      {
        id: '9',
        isActive: true,
        streets: ['Ferdinandstraße 32'],
        city: 'Hamburg',
        addressType: 'MAIN',
      },
    ],
  },
];

export const CardAddressData: any[] = [
  {
    streets: ['Alter Güterbahnhof 1b'],
    zipCode: '22303',
    city: 'Hamburg',
    countryCode: 'DE',
    addressName: 'Office',
    addressType: AddressTypeEnum.DELIVERY,
    isDefault: true,
    location: {
      lat: 53.54971200706458,
      lng: 9.968216616141591,
    },
  },
  {
    streets: ['Ferdinandstraße 32'],
    zipCode: '20095',
    city: 'Hamburg',
    countryCode: 'DE',
    addressName: 'My Home',
    addressType: AddressTypeEnum.DELIVERY,
    location: {
      lat: 53.54971200706458,
      lng: 9.968216616141591,
    },
  },
];

export const PaymentMethodData: PaymentMethodEntity[] = [
  {
    logoUrl: 'visa-white.svg',
    cardNo: '3280',
    cardHolder: 'Christian Puell',
    expires: '12/23',
    isDefault: true,
  },
  {
    logoUrl: 'mastercard.svg',
    cardNo: '3282',
    cardHolder: 'Christian Puell',
    expires: '12/23',
  },
];
