export const DIMENSION_DEPENDS_CONFIG: any = {
  GRAM: ['GRAM', 'KILOGRAM'],
  KILOGRAM: ['GRAM', 'KILOGRAM'],
  METER: ['METER', 'CENTIMETER'],
  CENTIMETER: ['METER', 'CENTIMETER'],
  LITER: ['LITER', 'MILLILITER'],
  MILLILITER: ['LITER', 'MILLILITER'],
  ITEM: ['ITEM'],
  LAUNDRY: ['LAUNDRY'],
  SHEET: ['SHEET'],
  PAIR: ['PAIR'],
};
