import { CardLink } from '../models/settings-card.model';

export const STORE_SETUP_MENU: CardLink[] = [
  { title: 'Basic information', path: 'basic-information' },
  { title: 'Picker and Driver limitations', path: 'picker-driver-limitations' },
  { title: 'Store contact', path: 'store-contact' },
  { title: 'Store Consultants', path: 'store-consultants' },
  { title: 'Store Address ', path: 'store-address' },
  { title: 'Store opening hours', path: 'store-opening-hours' },
  { title: 'Store pick durations', path: 'store-pick-durations' },
  { title: 'Store closing days', path: 'store-closing-days' },
  { title: 'Store Staff Bound', path: 'store-staff-bound' },
  { title: 'Store Loyalty Program', path: 'store-loyalty-program' },
  { title: 'Delivery weight option', path: 'weight-option' },
  { title: 'Delivery zone', path: 'delivery-zone' },
  { title: 'Delivery time', path: 'delivery-time' },
  { title: 'Instants Delivery Fee', path: 'instants-delivery-fee' },
  { title: 'Scheduled Delivery Fee', path: 'scheduled-delivery-fee' },
  { title: 'Delivery slots', path: 'store-delivery-slot' },
  { title: 'Delivery scheduler', path: 'store-scheduler' },
  { title: 'Store Social Media', path: 'store-social-media' },
  { title: 'Product Category and Groups', path: 'product-category-and-groups' },
  { title: 'Store Category Sort', path: 'product-category-sorting' },
  { title: 'Store Assets', path: 'store-assets' },
  { title: 'Shop Settings', path: 'shop-settings' },
  { title: 'Legal', path: 'legal' },
  { title: 'Billing Details', path: 'billing-details' },
  { title: 'Product Disclaimer', path: 'product-disclaimer' },
  { title: 'Product Link', path: 'product-link' },
  { title: 'Out Of Stock', path: 'out-of-stock' },
  { title: 'Category Out Of Stock Time', path: 'product-category-out-of-stock-time' },
  { title: 'Product Cart Limit', path: 'store-product-link-cart-limit' },
  { title: 'Commission Fee Store', path: 'store-commission-fee-store' },
  { title: 'Commission Fee Category', path: 'store-commission-fee-category' },
  { title: 'Commission Fee Subcategory', path: 'store-commission-fee-subcategory' },
  { title: 'Commission Fee Product', path: 'store-commission-fee-product' },
  { title: 'Product Recommendations', path: 'store-product-recommendations' },
  { title: 'Product Promotion', path: 'store-product-promotion' },
  { title: 'Notification Blocks', path: 'store-notification-blocks' },
  { title: 'Store Services', path: 'store-service-subs' },
];
